# @prettier
#on: push
on:
#  pull_request:
  pull_request_target:
    types:
      - closed
name: 'Test Find Issue Key'

jobs:
  test-find-issue-key:
    name: 'Find Issue Key'
    runs-on: ubuntu-20.04
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: 'gajira-find-issue-key'
      - name: Test
        run: |
          ls -lah
          ls -lah gajira-find-issue-key
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL || secrets.JIRA_EMAIL}}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN || secrets.JIRA_TOKEN}}

      - name: 'Find Issue Key'
        id: find
        uses: ./gajira-find-issue-key
        with:
          jira_base_url: ${{ secrets.JIRA_BASE_URL }}
          github-token: ${{github.token}}
#          include-merge-messages: true
          jira-transition-on-pr-merge: 'In Progress'
          jira-transition-on-pr-open: 'In Progress'
          jira-transition-on-pr-approval: 'In Progress'
          jira-transition-chain: 'In Progress'
#          from: string
#          string: NIC-6 | will search in branch name

#      - name: 'Find issue info'
#        shell: bash
#        env:
#          ISSUE_FOUND: ${{ steps.find.outputs.issue }}
#        run: |
#          echo "::info:: Issue ${ISSUE_FOUND} was found"
#
#          if [[ "${ISSUE_FOUND}" == "NIC-6" ]];then
#            echo "::info:: Issue ${ISSUE_FOUND} was found"
#          else
#            echo "::error:: Find issue from string failed"
#          fi



